### PR TITLE
⚠️ Work In Progress : Digital Signatures ✍️

### PR DESCRIPTION
**Pull request by itsbalamurali**
This is a Work in Progress PR for Implementation of [Digital Signatures](https://www.adobe.com/devnet-docs/acrobatetk/tools/DigSigDC/Acrobat_DigitalSignatures_in_PDF.pdf) into `gofpdf`. This PR is created to let know people that this future is currently being worked upon.

This PR soon will address issue no #115. 

The implementation is majorly inspired and ported from [TCPDF](https://tcpdf.org) [Example](https://tcpdf.org/examples/example_052/).

If you are interested in contributing to this PR, please create PR against my fork here (https://github.com/itsbalamurali/gofpdf/).

Looking for Contributors. 

Thanks,
Balamurali Pandranki.

### CODE REVIEW

**Comment by jung-kurt** [comment]
Thank you, @itsbalamurali

**Comment by jung-kurt** [comment]
@itsbalamurali -- let's re-open this when everything is working.

**Comment by evalsocket** [comment]
We are also looking for same solution in our project. Any help wanted ? @itsbalamurali

**Comment by evalsocket** [comment]
We are also looking for same solution in our project. Any update ? Any help wanted ? @itsbalamurali @jung-kurt

**Pull request closed without merging**
