### PR TITLE
UTF-8 support. Use AddUTF8Font to add TTF font with UTF-8 symbols.

### PR DESCRIPTION
**Pull request by ArtemKor**
See ExampleFpdf_AddUTF8Font for example.

This is based on tFPDF 1.25 implementation.

### CODE REVIEW

**Comment by jung-kurt** [comment]
Wow, @ArtemKor, this is a remarkable contribution. Many thanks!

The obstacle here is the license. tFPDF is licensed with the LGPL which will be a problem for many users of gofpdf. Maybe one way forward would be for you to fork the repository and I can place a prominent note on gofpdf's README sending people to your project if they're OK with LGPL. 

Your thoughts?

**Comment by OlegFX** [comment]
I'm not sure if we must keep tFPDF license here - this was done with an eye on the PHP tFPDF but in own way.

**Comment by ArtemKor** [comment]
Can we merge it keeping MIT license?

**Comment by jung-kurt** [comment]
> Can we merge it keeping MIT license?

I'd like to, but I want to make certain that we're doing so properly. Maybe we can have the author of tFPDF (I assume this is Ian Back who wrote the [original script](http://fpdf.org/en/script/script92.php)) view the diffs and give us his assurance that merging your Go adaptation doesn't violate his terms.

One way or another, your good work is valuable and needs to be available, either in this library with the MIT license or a fork with the more restrictive LGPL. Thanks again for your efforts -- the lack of UTF-8 support has been the biggest shortcoming in gofpdf.

**Comment by OlegFX** [comment]
I've sent a letter to Ian asking him to participate in this discussion.

**Comment by jung-kurt** [comment]
> I've sent a letter to Ian asking him to participate in this discussion.

Thanks, @OlegFX.

**Comment by jung-kurt** [comment]
If no contact has been made with the author of tFPDF, I think the best course forward is for @ArtemKor to begin a fork of this project and license it with LGPL. I can help with the details. Also, when this is complete I will add a prominent paragraph to the README that points package users to the new project.

**Comment by OlegFX** [comment]
@jung-kurt could you contact me by email: oleg@oleg.name to discuss it? We aren't ready to use LGPL license here because we added UTF-8 support as requirements for commercial project, also LGPL is a [bad choice](https://www.reddit.com/r/golang/comments/2xpulb/the_go_team_officially_recommends_vendoring/cp2dqj4/) for Go libraries.
I believe it should be free (MIT) even if we have to completely rewrite it.

**Comment by jung-kurt** [comment]
Have you followed issue #227? @d1ngd0 has done good work in blending gofpdf and gopdf. I don't believe the package is complete yet but Paul says the hard parts are complete. Both packages are released under the MIT licence.

**Comment by jung-kurt** [comment]
Outstanding contribution, @ArtemKor! I will likely have questions over the next few days before I merge.

Many thanks for your excellent work and willingness to accommodate this project's license requirements.

**Pull request closed without merging**
