### PR TITLE
Change current page of PDF document.

### PR DESCRIPTION
**Pull request by ykamo001**
Allows user to navigate through PDF document by changing the current page to the desired page if it's valid.

### CODE REVIEW

**Comment by jung-kurt** [comment]
Thanks, @ykamo001. Is the idea for this to be able to revisit pages during document generation? A short example demonstrating its use would be desirable.

**Comment by ykamo001** [comment]
Yes, absolutely! During document generation and editing. I'll give you the scenario and then the implementation. The reason I had to make this modification was because I was generating different graphs on different pages, but the X-axis and data points remained the same, however the Y-axis data changed. And so to save some unnecessary iterations through 2D arrays and slices, it's convenient to switch pages and make similar modifications on each page with different values.

Implementation Example:
Let's say we want to make a graph that plots Time Vs Temperature for each sensor we have.
Assume pdf has already been set up.

```
func example(pdf *gofpdf.Fpdf, time []float64,  temperaturesFromSensors[][]float64) {
        //Containers for holding the graphs and page numbers.
        var graphs []gofpdf.GridType
	var pageNums []int
        xMax := time[len(time) - 1] 
	for i , sensor := range temperaturesFromSensors {
                 //Create a new page and graph for each sensor we want to graph.
		pdf.AddPage()
		pdf.Ln(1)
                 //Custom label per sensor
		pdf.WriteAligned(0, 0, "Temperature Sensor "+strconv.Itoa(i+1)+" (\u2103) vs Time (min)", "C")
		pdf.Ln(0.5)
		graph := gofpdf.NewGrid(pdf.GetX(), pdf.GetY(), 20, 10)
		graph.TickmarksContainX(0, xMax)
                 //Custom Y axis
                 yMin := sensor[0]
                 yMax := sensor[len(sensor)-1]
		graph.TickmarksContainY(yMin, yMax)
		graph.Grid(pdf)
                //Save references and locations.
		graphs = append(graphs, graph)
		pageNums = append(pageNums, pdf.PageNo())
	}

	// For each X, graph the Y in each sensor.
	for i, currTime := range time {
		for j, sensor := range  temperaturesFromSensors{
			pdf.SetPage(pageNums[j])
			graph := graphs[j]
			temperature := sensor[i]
			pdf.Circle(graph.X(currTime), graph.Y(temperature), 0.04, "D")
		}
	}
}

```

Hope this example helps demonstrate its use! Let me know if you'd like me to add the example to the test file with some of the other examples.

**Comment by jung-kurt** [comment]
Excellent! Nice work. Yes, if you could sprinkle in some example data, adding your example to fpdf_test.go would be very welcome.

**Comment by jung-kurt** [comment]
Thank you very much, @ykamo001! Nice feature.

**Pull request merged**
