### PR TITLE
adding support to embedded fonts as byte array

### PR DESCRIPTION
**Pull request by prsolucoes**
I have added support to embedded fonts (from []byte). With this you can use "https://github.com/jteeuwen/go-bindata" to create the files from fonts.

I already it with success in my project:
https://github.com/prsolucoes/godiffexporter/blob/master/main.go

Advantages:
- Everything already is on memory
- The binary can be distributed without font files

Check my Makefile to see an example of how to generate the file with embedded fonts:
https://github.com/prsolucoes/godiffexporter/blob/master/Makefile

Thanks.

### CODE REVIEW

**Comment by jung-kurt** [comment]
Thanks, @prsolucoes, for a useful contribution. I'll merge it in when I think of the best way to demonstrate it for end-users. Probably this will be in the form of a test with sufficient  documentation to show how a Go resource file is created.

Nice work!

**Comment by prsolucoes** [comment]
Hi,

So i made the tests now to you merge it.

Thanks.

**Comment by jung-kurt** [comment]
Thanks @prsolucoes 

I isolated the rather large binary files to help with editing the test source file. Also, I used the calligra font to avoid copyright issues.

**Comment by jung-kurt** [comment]
@prsolucoes If you would like to be acknowledged in the README, what name should I use?

**Comment by prsolucoes** [comment]
Hi,

Thanks. You can use my name "Paulo Coutinho" if you want.

**Pull request merged**
