### PR TITLE
Strikeout: use "S" as styleStr

### PR DESCRIPTION
**Pull request by Rjinswand**
copied implementation of "underline" and set the line a little bit higher: text is striked-out

### CODE REVIEW

**Comment by jung-kurt** [comment]
Thanks @Rjinswand! Excellent feature.

Quick question about the modified import lines ("github.com/jung-kurt/gofpdf" -> "gofpdf"). Is this simplification made possible by the `replace github.com/jung-kurt/gopdf => ./` line in go.mod?

**Comment by jung-kurt** [comment]
`go vet -all` (run with `make check`) doesn't like the simplified import:

> imports gofpdf: malformed module path "gofpdf": missing dot in first path element

It may be best to stay with the fully qualified imports.

**Comment by Rjinswand** [comment]
to be honest: I don't know ;) I'm not so familiar with the build process of go

I could compile my fork since I couldn't import the "internal" directory from an external source. With my changes it works. 

`fpdf_test.go:37:2: use of internal package github.com/jung-kurt/gofpdf/internal/example not allowed`

**Comment by Rjinswand** [comment]
ah, there's a typo in go.mod: gopdf vs. gofpdf

**Comment by jung-kurt** [comment]
> ah, there's a typo in go.mod: gopdf vs. gofpdf

Right you are! I'll look into this.

**Comment by jung-kurt** [comment]
Thanks for contribution, @Rjinswand.

Import path adjustments have been an irritation when forking Go projects. The introduction of modules makes it a bit easier, see [When should I use the replace directive?](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive) for more details.

**Pull request merged**
