### PR TITLE
Fix for changing font byte array

### PR DESCRIPTION
**Pull request by ArtemKor**
The situation when the library changed the used byte array of the font is fixed.

### CODE REVIEW

**Comment by jung-kurt** [comment]
Thanks, @ArtemKor. Do you know why a copy of the font is required? Also, good catch on cleaning up the non-ASCII code point in `GenerateCutFont`.

**Comment by OlegFX** [comment]
Previously font slices were loaded to GoFPDF object using pdf.AddUTF8FontFromBytes method couldn't be used for another GoFPDF object because the data in this slice changed after PDF generation. Now one font slice can be used any number of times.

**Comment by ArtemKor** [comment]
This hotfix resolves this error. Now the byte array font is read-only and can be used many times.

**Comment by jung-kurt** [comment]
Thank you, @ArtemKor!

**Pull request merged**
