### PR TITLE
implement line join style

### PR DESCRIPTION
**Pull request by stanim**
I have an example which I will add later.
linecapjoin_inkscape

### CODE REVIEW

**Comment by jung-kurt** [comment]
Nice feature -- thanks!

**Comment by marcusatbang** [comment]
Should the magic strings (`"miter"`, `"round"` and `"bevel"`) be listed as package constants?

That may apply elsewhere in the project as well...

**Comment by jung-kurt** [comment]
Good point. At the expense of adding a namespace qualifier (for example, `gofpdf.Miter` or `gofpdf.CnMiter`) the compiler can make sure the argument has been entered correctly.

[This gist](https://gist.github.com/jung-kurt/38ed80b64ba7af6e5956) shows that a little bit of type safety could be added while remaining backwards compatible with ordinary strings.

**Comment by marcusatbang** [comment]
Type safe constants at no runtime cost - looks good.

I'm not fond of the `Cn` sigil though. Is there a Go standard for how constants should be named? Part of me wants to use CAPITAL_LETTERS for constants, but I know that's not Go-like.

**Comment by jung-kurt** [comment]
Camel-case seems to be the convention: http://stackoverflow.com/questions/22688906/go-naming-conventions-for-const

The advantage of the `Cn` prefix is that it helps distinguish the name from entry points.

**Comment by marcusatbang** [comment]
How about `JoinStyle_Miter`?

```go
pdf.SetLineJoinStyle(JoinStyle_Miter)
```

**Comment by jung-kurt** [comment]
golint complains: `don't use underscores in Go names; const draw_fill should be drawFill`

I have my share of problems with golint, but I have reached the conclusion that a clean golint report is worth doing things its way.

**Comment by marcusatbang** [comment]
Mumble grumble mutter fine...  :)

**Comment by marcusatbang** [comment]
I'd still favour something specific like `JoinStyleMiter` over the short `CnMiter`. I feel like we're several decades past the point where saving a couple of letters in an identifier makes sense.

**Comment by jung-kurt** [comment]
Agreed -- your point is well taken.

**Comment by marcusatbang** [comment]
I'll try and make sure the FPDI port follows whatever naming convention you decide on.

**Comment by jung-kurt** [comment]
Excellent. Let's go with your `JoinStyleMiter` suggestion and type them like this:
```
type JoinStyle string

const JoinStyleMiter = JoinStyle("miter")

func SetJoinStyle(style JoinStyle) {}
```
As we've seen, this is backwards compatible with ordinary strings. I'll make the changes to the existing API.

**Comment by marcusatbang** [comment]
:+1:

**Comment by marcusatbang** [comment]
And presumably something similar for other magic strings, such as:
```go
func (f *Fpdf) SetDisplayMode(zoomStr, layoutStr string) {
```
```go
func (f *Fpdf) AddPageFormat(orientationStr string, size SizeType) {
```
```go
func (f *Fpdf) SetLineCapStyle(styleStr string) {
```
...etc. It is extremely helpful that they're backwards compatible with `string`.

**Comment by jung-kurt** [comment]
The backwards compatibility is crucial -- the extra bit of type safety wouldn't be worth a breaking change.

I haven't looked at the entire API in this regard, but at least some arguments can be combined: `"F"`, `"D"`, `"FD"` for drawing. I favor making into constants all combinations rather than using concatenation. That is, 
```
DrawStyleFill = DrawStyle("F")
DrawStyleDraw = DrawStyle("D")
DrawStyleFillDraw = DrawStyle("FD")
```
rather than
 ```
DrawStyleFill + DrawStyleDraw
```

**Comment by stanim** [comment]
When I implemented this, I looked at SetLineCapStyle as a blueprint.
As SetJoinStyle
is introduced only a few days ago and probably nobody is using it yet, you
also could be free to implement it another way.
For SetLineCapStyle et alii this is of course too late.

**Comment by jung-kurt** [comment]
All of your work looks fine. The nice thing about changing the argument type from `string` to, say, `JoinStyle` (where `JoinStyle` is defined as `type JoinStyle string`) is that ordinary strings can still be used. Consequently, no existing code should break.

So, no need to change anything yet. Keep up the great work!

**Pull request merged**
